package com.holding.models;
// Generated 11 f�vr. 2023, 04:06:28 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrat generated by hbm2java
 */
@Entity
@Table(name = "contrat", catalog = "holding_bd")
public class Contrat implements java.io.Serializable {

	private Integer idContrat;
	private int idAppartement;
	private Date dateDebut;
	private Date dateFin;

	public Contrat() {
	}

	public Contrat(int idAppartement) {
		this.idAppartement = idAppartement;
	}

	public Contrat(int idAppartement, Date dateDebut, Date dateFin) {
		this.idAppartement = idAppartement;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_CONTRAT", unique = true, nullable = false)
	public Integer getIdContrat() {
		return this.idContrat;
	}

	public void setIdContrat(Integer idContrat) {
		this.idContrat = idContrat;
	}

	@Column(name = "ID_APPARTEMENT", nullable = false)
	public int getIdAppartement() {
		return this.idAppartement;
	}

	public void setIdAppartement(int idAppartement) {
		this.idAppartement = idAppartement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEBUT", length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN", length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

}
