package com.holding.models;
// Generated 11 f�vr. 2023, 04:06:28 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Immeuble generated by hbm2java
 */
@Entity
@Table(name = "immeuble", catalog = "holding_bd")
public class Immeuble implements java.io.Serializable {

	private Integer idImmeuble;
	private int idProprietaire;
	private String libelle;
	private String adresse;
	private Integer superficie;
	private Short nombreAppartement;
	private String type;
	private Boolean ascenseur;
	private Boolean stationnement;
	private Integer coutConstruction;
	private String photo;

	public Immeuble() {
	}

	public Immeuble(int idProprietaire) {
		this.idProprietaire = idProprietaire;
	}

	public Immeuble(int idProprietaire, String libelle, String adresse, Integer superficie, Short nombreAppartement,
			String type, Boolean ascenseur, Boolean stationnement, Integer coutConstruction, String photo) {
		this.idProprietaire = idProprietaire;
		this.libelle = libelle;
		this.adresse = adresse;
		this.superficie = superficie;
		this.nombreAppartement = nombreAppartement;
		this.type = type;
		this.ascenseur = ascenseur;
		this.stationnement = stationnement;
		this.coutConstruction = coutConstruction;
		this.photo = photo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_IMMEUBLE", unique = true, nullable = false)
	public Integer getIdImmeuble() {
		return this.idImmeuble;
	}

	public void setIdImmeuble(Integer idImmeuble) {
		this.idImmeuble = idImmeuble;
	}

	@Column(name = "ID_PROPRIETAIRE", nullable = false)
	public int getIdProprietaire() {
		return this.idProprietaire;
	}

	public void setIdProprietaire(int idProprietaire) {
		this.idProprietaire = idProprietaire;
	}

	@Column(name = "LIBELLE", length = 25)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@Column(name = "ADRESSE", length = 25)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "SUPERFICIE")
	public Integer getSuperficie() {
		return this.superficie;
	}

	public void setSuperficie(Integer superficie) {
		this.superficie = superficie;
	}

	@Column(name = "NOMBRE_APPARTEMENT")
	public Short getNombreAppartement() {
		return this.nombreAppartement;
	}

	public void setNombreAppartement(Short nombreAppartement) {
		this.nombreAppartement = nombreAppartement;
	}

	@Column(name = "TYPE", length = 25)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "ASCENSEUR")
	public Boolean getAscenseur() {
		return this.ascenseur;
	}

	public void setAscenseur(Boolean ascenseur) {
		this.ascenseur = ascenseur;
	}

	@Column(name = "STATIONNEMENT")
	public Boolean getStationnement() {
		return this.stationnement;
	}

	public void setStationnement(Boolean stationnement) {
		this.stationnement = stationnement;
	}

	@Column(name = "COUT_CONSTRUCTION")
	public Integer getCoutConstruction() {
		return this.coutConstruction;
	}

	public void setCoutConstruction(Integer coutConstruction) {
		this.coutConstruction = coutConstruction;
	}

	@Column(name = "PHOTO")
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

}
