package com.holding.models;
// Generated 11 f�vr. 2023, 04:06:28 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Locataire generated by hbm2java
 */
@Entity
@Table(name = "locataire", catalog = "holding_bd")
public class Locataire implements java.io.Serializable {

	private Integer idLocataire;
	private int idContrat;
	private String nom;
	private String prenom;
	private String typePiece;
	private String numeroPiece;
	private String adresse;
	private Integer telephone;
	private String email;
	private String photo;

	public Locataire() {
	}

	public Locataire(int idContrat) {
		this.idContrat = idContrat;
	}

	public Locataire(int idContrat, String nom, String prenom, String typePiece, String numeroPiece, String adresse,
			Integer telephone, String email, String photo) {
		this.idContrat = idContrat;
		this.nom = nom;
		this.prenom = prenom;
		this.typePiece = typePiece;
		this.numeroPiece = numeroPiece;
		this.adresse = adresse;
		this.telephone = telephone;
		this.email = email;
		this.photo = photo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_LOCATAIRE", unique = true, nullable = false)
	public Integer getIdLocataire() {
		return this.idLocataire;
	}

	public void setIdLocataire(Integer idLocataire) {
		this.idLocataire = idLocataire;
	}

	@Column(name = "ID_CONTRAT", nullable = false)
	public int getIdContrat() {
		return this.idContrat;
	}

	public void setIdContrat(int idContrat) {
		this.idContrat = idContrat;
	}

	@Column(name = "NOM", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 45)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "TYPE_PIECE", length = 20)
	public String getTypePiece() {
		return this.typePiece;
	}

	public void setTypePiece(String typePiece) {
		this.typePiece = typePiece;
	}

	@Column(name = "NUMERO_PIECE", length = 20)
	public String getNumeroPiece() {
		return this.numeroPiece;
	}

	public void setNumeroPiece(String numeroPiece) {
		this.numeroPiece = numeroPiece;
	}

	@Column(name = "ADRESSE", length = 25)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "TELEPHONE")
	public Integer getTelephone() {
		return this.telephone;
	}

	public void setTelephone(Integer telephone) {
		this.telephone = telephone;
	}

	@Column(name = "EMAIL", length = 25)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHOTO", length = 75)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

}
